//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLibrary.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Travel
    {
        public int Id { get; set; }
        public int AgencyID { get; set; }
        public string Titular { get; set; }
        public int Destination { get; set; }
        public int Hotel { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal TotalCost { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
    
        public virtual Agency Agency { get; set; }
    }
}
